grocery_list_app/urls.py
from django.urls import path

from . import views

app_name = 'grocery_list_app'

urlpatterns = [
  path('', views.index, name='index'),
  path('add/', views.add, name='add'),
  path('complete/<int:pk>/', views.complete, name='complete'),
  path('delete/<int:pk>', views.delete, name='delete'),
]

grocery_list_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grocery_list_app.urls'))
]

grocery_list_app/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class GroceryItem(models.Model):
  text_description = models.CharField(max_length=200)
  created_date = models.DateTimeField()
  completed_date = models.DateTimeField(null=True, blank=True)
  completed = models.BooleanField(default=False)

  def __str__(self):
    return self.text_description



# a model called GroceryItem which contains a text description, a created date, a completed date, and a boolean representing whether it was completed

grocery_list_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
# from django.template import loader
from django.utils import timezone
from .models import GroceryItem

# Create your views here.
def index(request):
  # template = loader.get_template('grocery_list/index.html')
  # form = GroceryItemForm()
  incompleted_items = GroceryItem.objects.filter(completed=False).order_by('created_date')
  completed_items = GroceryItem.objects.filter(completed=True).order_by('completed_date')
  context = {
    'incompleted_items': incompleted_items,
    'completed_items': completed_items
  }
  # return HttpResponse(template.render(context, request))
  return render(request, 'grocery_list/index.html', context)


def add(request):
  if request.POST['text_description']:
    GroceryItem.objects.create(created_date=timezone.now(), text_description=request.POST['text_description'])
  # template = loader.get_template('item.html')
  # context = {
  #   'item': grocery
  # }
  # return HttpResponse(template.render(context, request))
  return HttpResponseRedirect(reverse('grocery_list_app:index'))

def complete(request, pk):
  item = get_object_or_404(GroceryItem, pk=pk)
  if item.completed:
    item.completed = False
    item.completed_date = None
  else:
    item.completed = True
    item.completed_date = timezone.now()
  item.save()
  return HttpResponseRedirect(reverse('grocery_list_app:index'))

def delete(request, pk):
  item = get_object_or_404(GroceryItem, pk=pk)
  item.delete()
  return HttpResponseRedirect(reverse('grocery_list_app:index'))

grocery_list_app/templates/grocery_list/index.html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grocery List App</title>
  </head>
  <body>
    <h1>Grocery List</h1>

    <form method="post" action="{% url 'grocery_list_app:add' %}">
      {% csrf_token %}
      <label for="text_description">Description:</label>
      <input type="text" id="text_description" name="text_description">
      <input type="submit" value="Create Grocery List">
    </form>

      <h2>Incomplete</h2>
      {% for item in incompleted_items %}
        <p>
        {{ item.text_description }}
        <form action="{% url 'grocery_list_app:complete' item.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="complete">
        </form>
        <form action="{% url 'grocery_list_app:delete' item.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="delete">
        </form>
        </p>
      {% endfor %}

      <h2>Complete</h2>
      {% for item in completed_items %}
        <p>
        {{ item.text_description }}
        <form action="{% url 'grocery_list_app:complete' item.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="complete">
        </form>
        <form action="{% url 'grocery_list_app:delete' item.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="delete">
        </form>
        </p>
      {% endfor %}
  </body>
</html>